"""Pytest fixtures for mcap-reader tests.

Provides temporary MCAP files generated by the synthetic generators.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.generators.generate_mcap import (
    generate_image_mcap,
    generate_imu_mcap,
    generate_joint_state_mcap,
    generate_multi_episode_mcap,
    generate_multi_topic_mcap,
    generate_tf_mcap,
)


@pytest.fixture
def imu_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP file with 100 IMU messages at 200 Hz."""
    return generate_imu_mcap(tmp_path / "imu.mcap", num_messages=100, rate_hz=200)


@pytest.fixture
def joint_state_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP file with 100 JointState messages at 50 Hz."""
    return generate_joint_state_mcap(
        tmp_path / "joints.mcap",
        num_messages=100,
        rate_hz=50,
        joint_names=["joint1", "joint2"],
    )


@pytest.fixture
def image_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP file with 10 Image messages."""
    return generate_image_mcap(
        tmp_path / "image.mcap",
        num_messages=10,
        height=480,
        width=640,
        encoding="rgb8",
    )


@pytest.fixture
def image_mono_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP file with 5 mono8 Image messages."""
    return generate_image_mcap(
        tmp_path / "image_mono.mcap",
        num_messages=5,
        height=100,
        width=100,
        encoding="mono8",
    )


@pytest.fixture
def tf_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP file with 50 TF messages."""
    return generate_tf_mcap(
        tmp_path / "tf.mcap",
        num_messages=50,
        frames=[("world", "base_link"), ("base_link", "camera")],
    )


@pytest.fixture
def multi_topic_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP file with IMU + JointState + TF."""
    return generate_multi_topic_mcap(tmp_path / "multi.mcap")


@pytest.fixture
def multi_episode_mcap(tmp_path: Path) -> Path:
    """Generate a temporary MCAP with 3 episodes separated by 10s gaps."""
    return generate_multi_episode_mcap(
        tmp_path / "episodes.mcap",
        num_episodes=3,
        gap_seconds=10.0,
    )
